# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from carbon.paths.auth_v1_access_token.get import GetAccessTokenRaw
from carbon.paths.auth_v1_white_labeling.get import GetWhiteLabelingRaw


class AuthApiRaw(
    GetAccessTokenRaw,
    GetWhiteLabelingRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
