# coding: utf-8
"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from carbon.paths.delete_users.post import Delete
from carbon.paths.user.post import Get
from carbon.paths.list_users.post import List
from carbon.paths.modify_user_configuration.post import ToggleUserFeatures
from carbon.paths.update_users.post import UpdateUsers
from carbon.apis.tags.users_api_raw import UsersApiRaw


class UsersApiGenerated(
    Delete,
    Get,
    List,
    ToggleUserFeatures,
    UpdateUsers,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
