# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import carbon
from carbon.model.organization_user_files_to_sync_filters_external_file_ids import OrganizationUserFilesToSyncFiltersExternalFileIds
from carbon import configuration


class TestOrganizationUserFilesToSyncFiltersExternalFileIds(unittest.TestCase):
    """OrganizationUserFilesToSyncFiltersExternalFileIds unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
