# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import carbon
from carbon.model.leads_response import LeadsResponse
from carbon import configuration


class TestLeadsResponse(unittest.TestCase):
    """LeadsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
