# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import carbon
from carbon.model.embeddings_and_chunks_filters import EmbeddingsAndChunksFilters
from carbon import configuration


class TestEmbeddingsAndChunksFilters(unittest.TestCase):
    """EmbeddingsAndChunksFilters unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
