name: Carbon
targets:
  Carbon:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Carbon]
    info:
      path: ./Info.plist
      version: 0.2.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable