# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from carbon import schemas  # noqa: F401


class ConnectDataSourceResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "sync_url",
            "data_source",
        }
        
        class properties:
        
            @staticmethod
            def data_source() -> typing.Type['OrganizationUserDataSourceAPI']:
                return OrganizationUserDataSourceAPI
            
            
            class sync_url(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sync_url':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "data_source": data_source,
                "sync_url": sync_url,
            }
    
    sync_url: MetaOapg.properties.sync_url
    data_source: 'OrganizationUserDataSourceAPI'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["data_source"]) -> 'OrganizationUserDataSourceAPI': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sync_url"]) -> MetaOapg.properties.sync_url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["data_source", "sync_url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["data_source"]) -> 'OrganizationUserDataSourceAPI': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sync_url"]) -> MetaOapg.properties.sync_url: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["data_source", "sync_url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        sync_url: typing.Union[MetaOapg.properties.sync_url, None, str, ],
        data_source: 'OrganizationUserDataSourceAPI',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConnectDataSourceResponse':
        return super().__new__(
            cls,
            *args,
            sync_url=sync_url,
            data_source=data_source,
            _configuration=_configuration,
            **kwargs,
        )

from carbon.model.organization_user_data_source_api import OrganizationUserDataSourceAPI
