# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from carbon import schemas  # noqa: F401


class ParsedTextFormatsNullable(
    schemas.EnumBase,
    schemas.StrBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneStrMixin
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The format in which the text content of the file should be parsed. Notion files are the only files
        that support this feature. The default parsed text format is plain text.
    """


    class MetaOapg:
        enum_value_to_name = {
            "PLAIN_TEXT": "PLAIN_TEXT",
            "MARKDOWN": "MARKDOWN",
        }
    
    @schemas.classproperty
    def PLAIN_TEXT(cls):
        return cls("PLAIN_TEXT")
    
    @schemas.classproperty
    def MARKDOWN(cls):
        return cls("MARKDOWN")


    def __new__(
        cls,
        *args: typing.Union[None, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ParsedTextFormatsNullable':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )
