/*
Carbon

Connect external data to LLMs, no matter the source.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommitUserNullable } from './commit-user-nullable';
import { Tree } from './tree';

/**
 * 
 * @export
 * @interface Commit
 */
export interface Commit {
    /**
     * 
     * @type {CommitUserNullable}
     * @memberof Commit
     */
    'author': CommitUserNullable | null;
    /**
     * 
     * @type {CommitUserNullable}
     * @memberof Commit
     */
    'committer': CommitUserNullable | null;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    'message': string;
    /**
     * 
     * @type {Tree}
     * @memberof Commit
     */
    'tree': Tree;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof Commit
     */
    'comment_count': number;
}

