/*
Carbon

Connect external data to LLMs, no matter the source.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConfluenceAuthentication
 */
export interface ConfluenceAuthentication {
    /**
     * 
     * @type {any}
     * @memberof ConfluenceAuthentication
     */
    'source': any;
    /**
     * 
     * @type {string}
     * @memberof ConfluenceAuthentication
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof ConfluenceAuthentication
     */
    'refresh_token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConfluenceAuthentication
     */
    'subdomain': string;
}

