/*
Carbon

Connect external data to LLMs, no matter the source.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type ExternalFileSyncStatuses = 'DELAYED' | 'QUEUED_FOR_SYNC' | 'SYNCING' | 'READY' | 'SYNC_ERROR' | 'EVALUATING_RESYNC' | 'RATE_LIMITED' | 'SYNC_ABORTED' | 'QUEUED_FOR_OCR'

