/*
Carbon

Connect external data to LLMs, no matter the source.

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package carbon

import (
	"encoding/json"
)

// S3AuthRequest struct for S3AuthRequest
type S3AuthRequest struct {
	AccessKey string `json:"access_key"`
	AccessKeySecret string `json:"access_key_secret"`
	// Enabling this flag will fetch all available content from the source to be listed via list items endpoint
	SyncSourceItems *bool `json:"sync_source_items,omitempty"`
	// You can specify a Digital Ocean endpoint URL to connect a Digital Ocean Space through this endpoint.         The URL should be of format <region>.digitaloceanspaces.com. It's not required for S3 buckets.
	EndpointUrl NullableString `json:"endpoint_url,omitempty"`
	// Tags to be associated with the data source. If the data source already has tags set, then an upsert will be performed.
	DataSourceTags map[string]interface{} `json:"data_source_tags,omitempty"`
}

// NewS3AuthRequest instantiates a new S3AuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3AuthRequest(accessKey string, accessKeySecret string) *S3AuthRequest {
	this := S3AuthRequest{}
	this.AccessKey = accessKey
	this.AccessKeySecret = accessKeySecret
	var syncSourceItems bool = true
	this.SyncSourceItems = &syncSourceItems
	return &this
}

// NewS3AuthRequestWithDefaults instantiates a new S3AuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3AuthRequestWithDefaults() *S3AuthRequest {
	this := S3AuthRequest{}
	var syncSourceItems bool = true
	this.SyncSourceItems = &syncSourceItems
	return &this
}

// GetAccessKey returns the AccessKey field value
func (o *S3AuthRequest) GetAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value
// and a boolean to check if the value has been set.
func (o *S3AuthRequest) GetAccessKeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AccessKey, true
}

// SetAccessKey sets field value
func (o *S3AuthRequest) SetAccessKey(v string) {
	o.AccessKey = v
}

// GetAccessKeySecret returns the AccessKeySecret field value
func (o *S3AuthRequest) GetAccessKeySecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeySecret
}

// GetAccessKeySecretOk returns a tuple with the AccessKeySecret field value
// and a boolean to check if the value has been set.
func (o *S3AuthRequest) GetAccessKeySecretOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AccessKeySecret, true
}

// SetAccessKeySecret sets field value
func (o *S3AuthRequest) SetAccessKeySecret(v string) {
	o.AccessKeySecret = v
}

// GetSyncSourceItems returns the SyncSourceItems field value if set, zero value otherwise.
func (o *S3AuthRequest) GetSyncSourceItems() bool {
	if o == nil || isNil(o.SyncSourceItems) {
		var ret bool
		return ret
	}
	return *o.SyncSourceItems
}

// GetSyncSourceItemsOk returns a tuple with the SyncSourceItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3AuthRequest) GetSyncSourceItemsOk() (*bool, bool) {
	if o == nil || isNil(o.SyncSourceItems) {
    return nil, false
	}
	return o.SyncSourceItems, true
}

// HasSyncSourceItems returns a boolean if a field has been set.
func (o *S3AuthRequest) HasSyncSourceItems() bool {
	if o != nil && !isNil(o.SyncSourceItems) {
		return true
	}

	return false
}

// SetSyncSourceItems gets a reference to the given bool and assigns it to the SyncSourceItems field.
func (o *S3AuthRequest) SetSyncSourceItems(v bool) {
	o.SyncSourceItems = &v
}

// GetEndpointUrl returns the EndpointUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3AuthRequest) GetEndpointUrl() string {
	if o == nil || isNil(o.EndpointUrl.Get()) {
		var ret string
		return ret
	}
	return *o.EndpointUrl.Get()
}

// GetEndpointUrlOk returns a tuple with the EndpointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3AuthRequest) GetEndpointUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.EndpointUrl.Get(), o.EndpointUrl.IsSet()
}

// HasEndpointUrl returns a boolean if a field has been set.
func (o *S3AuthRequest) HasEndpointUrl() bool {
	if o != nil && o.EndpointUrl.IsSet() {
		return true
	}

	return false
}

// SetEndpointUrl gets a reference to the given NullableString and assigns it to the EndpointUrl field.
func (o *S3AuthRequest) SetEndpointUrl(v string) {
	o.EndpointUrl.Set(&v)
}
// SetEndpointUrlNil sets the value for EndpointUrl to be an explicit nil
func (o *S3AuthRequest) SetEndpointUrlNil() {
	o.EndpointUrl.Set(nil)
}

// UnsetEndpointUrl ensures that no value is present for EndpointUrl, not even an explicit nil
func (o *S3AuthRequest) UnsetEndpointUrl() {
	o.EndpointUrl.Unset()
}

// GetDataSourceTags returns the DataSourceTags field value if set, zero value otherwise.
func (o *S3AuthRequest) GetDataSourceTags() map[string]interface{} {
	if o == nil || isNil(o.DataSourceTags) {
		var ret map[string]interface{}
		return ret
	}
	return o.DataSourceTags
}

// GetDataSourceTagsOk returns a tuple with the DataSourceTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3AuthRequest) GetDataSourceTagsOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.DataSourceTags) {
    return map[string]interface{}{}, false
	}
	return o.DataSourceTags, true
}

// HasDataSourceTags returns a boolean if a field has been set.
func (o *S3AuthRequest) HasDataSourceTags() bool {
	if o != nil && !isNil(o.DataSourceTags) {
		return true
	}

	return false
}

// SetDataSourceTags gets a reference to the given map[string]interface{} and assigns it to the DataSourceTags field.
func (o *S3AuthRequest) SetDataSourceTags(v map[string]interface{}) {
	o.DataSourceTags = v
}

func (o S3AuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["access_key"] = o.AccessKey
	}
	if true {
		toSerialize["access_key_secret"] = o.AccessKeySecret
	}
	if !isNil(o.SyncSourceItems) {
		toSerialize["sync_source_items"] = o.SyncSourceItems
	}
	if o.EndpointUrl.IsSet() {
		toSerialize["endpoint_url"] = o.EndpointUrl.Get()
	}
	if !isNil(o.DataSourceTags) {
		toSerialize["data_source_tags"] = o.DataSourceTags
	}
	return json.Marshal(toSerialize)
}

type NullableS3AuthRequest struct {
	value *S3AuthRequest
	isSet bool
}

func (v NullableS3AuthRequest) Get() *S3AuthRequest {
	return v.value
}

func (v *NullableS3AuthRequest) Set(val *S3AuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableS3AuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableS3AuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3AuthRequest(val *S3AuthRequest) *NullableS3AuthRequest {
	return &NullableS3AuthRequest{value: val, isSet: true}
}

func (v NullableS3AuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3AuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


