/*
Carbon

Connect external data to LLMs, no matter the source.

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package carbon

import (
	"encoding/json"
	"os"
)

// BodyCreateUploadFileUploadfilePost struct for BodyCreateUploadFileUploadfilePost
type BodyCreateUploadFileUploadfilePost struct {
	File *os.File `json:"file"`
}

// NewBodyCreateUploadFileUploadfilePost instantiates a new BodyCreateUploadFileUploadfilePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyCreateUploadFileUploadfilePost(file *os.File) *BodyCreateUploadFileUploadfilePost {
	this := BodyCreateUploadFileUploadfilePost{}
	this.File = file
	return &this
}

// NewBodyCreateUploadFileUploadfilePostWithDefaults instantiates a new BodyCreateUploadFileUploadfilePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyCreateUploadFileUploadfilePostWithDefaults() *BodyCreateUploadFileUploadfilePost {
	this := BodyCreateUploadFileUploadfilePost{}
	return &this
}

// GetFile returns the File field value
func (o *BodyCreateUploadFileUploadfilePost) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *BodyCreateUploadFileUploadfilePost) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *BodyCreateUploadFileUploadfilePost) SetFile(v *os.File) {
	o.File = v
}

func (o BodyCreateUploadFileUploadfilePost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableBodyCreateUploadFileUploadfilePost struct {
	value *BodyCreateUploadFileUploadfilePost
	isSet bool
}

func (v NullableBodyCreateUploadFileUploadfilePost) Get() *BodyCreateUploadFileUploadfilePost {
	return v.value
}

func (v *NullableBodyCreateUploadFileUploadfilePost) Set(val *BodyCreateUploadFileUploadfilePost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyCreateUploadFileUploadfilePost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyCreateUploadFileUploadfilePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyCreateUploadFileUploadfilePost(val *BodyCreateUploadFileUploadfilePost) *NullableBodyCreateUploadFileUploadfilePost {
	return &NullableBodyCreateUploadFileUploadfilePost{value: val, isSet: true}
}

func (v NullableBodyCreateUploadFileUploadfilePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyCreateUploadFileUploadfilePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


