# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHybridSearchTuningParamsNullable(TypedDict):
    weight_a: typing.Union[int, float]

    weight_b: typing.Union[int, float]

class OptionalHybridSearchTuningParamsNullable(TypedDict, total=False):
    pass

class HybridSearchTuningParamsNullable(RequiredHybridSearchTuningParamsNullable, OptionalHybridSearchTuningParamsNullable):
    pass
