# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from carbon.type.organization_user_file_tag_create_tags import OrganizationUserFileTagCreateTags

class RequiredOrganizationUserFileTagCreate(TypedDict):
    tags: OrganizationUserFileTagCreateTags

    organization_user_file_id: int

class OptionalOrganizationUserFileTagCreate(TypedDict, total=False):
    pass

class OrganizationUserFileTagCreate(RequiredOrganizationUserFileTagCreate, OptionalOrganizationUserFileTagCreate):
    pass
