# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from carbon.pydantic.embeddings_and_chunks_filters import EmbeddingsAndChunksFilters
from carbon.pydantic.embeddings_and_chunks_order_by_columns import EmbeddingsAndChunksOrderByColumns
from carbon.pydantic.order_dir import OrderDir
from carbon.pydantic.pagination import Pagination

class EmbeddingsAndChunksQueryInput(BaseModel):
    filters: EmbeddingsAndChunksFilters = Field(alias='filters')

    pagination: typing.Optional[Pagination] = Field(None, alias='pagination')

    order_by: typing.Optional[EmbeddingsAndChunksOrderByColumns] = Field(None, alias='order_by')

    order_dir: typing.Optional[OrderDir] = Field(None, alias='order_dir')

    include_vectors: typing.Optional[bool] = Field(None, alias='include_vectors')
    class Config:
        arbitrary_types_allowed = True
