# coding: utf-8

"""
    Carbon

    Connect external data to LLMs, no matter the source.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from carbon.pydantic.external_source_items_order_by import ExternalSourceItemsOrderBy
from carbon.pydantic.list_items_filters_nullable import ListItemsFiltersNullable
from carbon.pydantic.order_dir_v2 import OrderDirV2
from carbon.pydantic.pagination import Pagination

class ListDataSourceItemsRequest(BaseModel):
    data_source_id: int = Field(alias='data_source_id')

    parent_id: typing.Optional[typing.Optional[str]] = Field(None, alias='parent_id')

    filters: typing.Optional[ListItemsFiltersNullable] = Field(None, alias='filters')

    pagination: typing.Optional[Pagination] = Field(None, alias='pagination')

    order_by: typing.Optional[ExternalSourceItemsOrderBy] = Field(None, alias='order_by')

    order_dir: typing.Optional[OrderDirV2] = Field(None, alias='order_dir')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
