//
// SimpleOAuthDataSources.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SimpleOAuthDataSources: String, Codable, CaseIterable {
    case googleDrive = "GOOGLE_DRIVE"
    case intercom = "INTERCOM"
    case dropbox = "DROPBOX"
    case onedrive = "ONEDRIVE"
    case box = "BOX"
    case gmail = "GMAIL"
    case outlook = "OUTLOOK"
}
