//
// YoutubeTranscriptResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct YoutubeTranscriptResponse: Codable, JSONEncodable, Hashable {

    public var status: String
    public var error: String?
    public var data: String?
    public var rawTranscript: [[String: RawTranscriptPropertyInnerValue]]?

    public init(status: String, error: String?, data: String?, rawTranscript: [[String: RawTranscriptPropertyInnerValue]]?) {
        self.status = status
        self.error = error
        self.data = data
        self.rawTranscript = rawTranscript
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case error
        case data
        case rawTranscript = "raw_transcript"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(error, forKey: .error)
        try container.encode(data, forKey: .data)
        try container.encode(rawTranscript, forKey: .rawTranscript)
    }
}

