/*
 * Carbon
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.carbonai.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.carbonai.client.model.EmbeddingsAndChunksFilters;
import com.konfigthis.carbonai.client.model.EmbeddingsAndChunksOrderByColumns;
import com.konfigthis.carbonai.client.model.OrderDir;
import com.konfigthis.carbonai.client.model.Pagination;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.carbonai.client.JSON;

/**
 * EmbeddingsAndChunksQueryInput
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EmbeddingsAndChunksQueryInput {
  public static final String SERIALIZED_NAME_PAGINATION = "pagination";
  @SerializedName(SERIALIZED_NAME_PAGINATION)
  private Pagination pagination;

  public static final String SERIALIZED_NAME_ORDER_BY = "order_by";
  @SerializedName(SERIALIZED_NAME_ORDER_BY)
  private EmbeddingsAndChunksOrderByColumns orderBy;

  public static final String SERIALIZED_NAME_ORDER_DIR = "order_dir";
  @SerializedName(SERIALIZED_NAME_ORDER_DIR)
  private OrderDir orderDir;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private EmbeddingsAndChunksFilters filters;

  public static final String SERIALIZED_NAME_INCLUDE_VECTORS = "include_vectors";
  @SerializedName(SERIALIZED_NAME_INCLUDE_VECTORS)
  private Boolean includeVectors = false;

  public EmbeddingsAndChunksQueryInput() {
  }

  public EmbeddingsAndChunksQueryInput pagination(Pagination pagination) {
    
    
    
    
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Pagination getPagination() {
    return pagination;
  }


  public void setPagination(Pagination pagination) {
    
    
    
    this.pagination = pagination;
  }


  public EmbeddingsAndChunksQueryInput orderBy(EmbeddingsAndChunksOrderByColumns orderBy) {
    
    
    
    
    this.orderBy = orderBy;
    return this;
  }

   /**
   * Get orderBy
   * @return orderBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EmbeddingsAndChunksOrderByColumns getOrderBy() {
    return orderBy;
  }


  public void setOrderBy(EmbeddingsAndChunksOrderByColumns orderBy) {
    
    
    
    this.orderBy = orderBy;
  }


  public EmbeddingsAndChunksQueryInput orderDir(OrderDir orderDir) {
    
    
    
    
    this.orderDir = orderDir;
    return this;
  }

   /**
   * Get orderDir
   * @return orderDir
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrderDir getOrderDir() {
    return orderDir;
  }


  public void setOrderDir(OrderDir orderDir) {
    
    
    
    this.orderDir = orderDir;
  }


  public EmbeddingsAndChunksQueryInput filters(EmbeddingsAndChunksFilters filters) {
    
    
    
    
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public EmbeddingsAndChunksFilters getFilters() {
    return filters;
  }


  public void setFilters(EmbeddingsAndChunksFilters filters) {
    
    
    
    this.filters = filters;
  }


  public EmbeddingsAndChunksQueryInput includeVectors(Boolean includeVectors) {
    
    
    
    
    this.includeVectors = includeVectors;
    return this;
  }

   /**
   * Get includeVectors
   * @return includeVectors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getIncludeVectors() {
    return includeVectors;
  }


  public void setIncludeVectors(Boolean includeVectors) {
    
    
    
    this.includeVectors = includeVectors;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EmbeddingsAndChunksQueryInput instance itself
   */
  public EmbeddingsAndChunksQueryInput putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddingsAndChunksQueryInput embeddingsAndChunksQueryInput = (EmbeddingsAndChunksQueryInput) o;
    return Objects.equals(this.pagination, embeddingsAndChunksQueryInput.pagination) &&
        Objects.equals(this.orderBy, embeddingsAndChunksQueryInput.orderBy) &&
        Objects.equals(this.orderDir, embeddingsAndChunksQueryInput.orderDir) &&
        Objects.equals(this.filters, embeddingsAndChunksQueryInput.filters) &&
        Objects.equals(this.includeVectors, embeddingsAndChunksQueryInput.includeVectors)&&
        Objects.equals(this.additionalProperties, embeddingsAndChunksQueryInput.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, orderBy, orderDir, filters, includeVectors, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddingsAndChunksQueryInput {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    orderDir: ").append(toIndentedString(orderDir)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    includeVectors: ").append(toIndentedString(includeVectors)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pagination");
    openapiFields.add("order_by");
    openapiFields.add("order_dir");
    openapiFields.add("filters");
    openapiFields.add("include_vectors");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("filters");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EmbeddingsAndChunksQueryInput
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EmbeddingsAndChunksQueryInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmbeddingsAndChunksQueryInput is not found in the empty JSON string", EmbeddingsAndChunksQueryInput.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EmbeddingsAndChunksQueryInput.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `pagination`
      if (jsonObj.get("pagination") != null && !jsonObj.get("pagination").isJsonNull()) {
        Pagination.validateJsonObject(jsonObj.getAsJsonObject("pagination"));
      }
      // validate the required field `filters`
      EmbeddingsAndChunksFilters.validateJsonObject(jsonObj.getAsJsonObject("filters"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmbeddingsAndChunksQueryInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmbeddingsAndChunksQueryInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmbeddingsAndChunksQueryInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmbeddingsAndChunksQueryInput.class));

       return (TypeAdapter<T>) new TypeAdapter<EmbeddingsAndChunksQueryInput>() {
           @Override
           public void write(JsonWriter out, EmbeddingsAndChunksQueryInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null) {
                   obj.addProperty(entry.getKey(), (String) null);
                 } else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EmbeddingsAndChunksQueryInput read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EmbeddingsAndChunksQueryInput instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmbeddingsAndChunksQueryInput given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmbeddingsAndChunksQueryInput
  * @throws IOException if the JSON string is invalid with respect to EmbeddingsAndChunksQueryInput
  */
  public static EmbeddingsAndChunksQueryInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmbeddingsAndChunksQueryInput.class);
  }

 /**
  * Convert an instance of EmbeddingsAndChunksQueryInput to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

