/*
 * Carbon
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.carbonai.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ExternalDataSourceType
 */
@JsonAdapter(ExternalDataSourceType.Adapter.class)public enum ExternalDataSourceType {
  
  BOX("BOX"),
  
  CONFLUENCE("CONFLUENCE"),
  
  DROPBOX("DROPBOX"),
  
  GMAIL("GMAIL"),
  
  GOOGLE_DRIVE("GOOGLE_DRIVE"),
  
  GOOGLE_CLOUD_STORAGE("GOOGLE_CLOUD_STORAGE"),
  
  INTERCOM("INTERCOM"),
  
  NOTION("NOTION"),
  
  ONEDRIVE("ONEDRIVE"),
  
  OUTLOOK("OUTLOOK"),
  
  SALESFORCE("SALESFORCE"),
  
  SHAREPOINT("SHAREPOINT"),
  
  SLACK("SLACK"),
  
  ZENDESK("ZENDESK"),
  
  ZOTERO("ZOTERO"),
  
  SERVICENOW("SERVICENOW");

  private String value;

  ExternalDataSourceType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ExternalDataSourceType fromValue(String value) {
    for (ExternalDataSourceType b : ExternalDataSourceType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ExternalDataSourceType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ExternalDataSourceType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ExternalDataSourceType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ExternalDataSourceType.fromValue(value);
    }
  }
}

