/*
 * Carbon
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.carbonai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataSourceConfiguration
 */
public class DataSourceConfigurationTest {
    private final DataSourceConfiguration model = new DataSourceConfiguration();

    /**
     * Model tests for DataSourceConfiguration
     */
    @Test
    public void testDataSourceConfiguration() {
        // TODO: test DataSourceConfiguration
    }

    /**
     * Test the property 'allowedFileFormats'
     */
    @Test
    public void allowedFileFormatsTest() {
        // TODO: test allowedFileFormats
    }

    /**
     * Test the property 'googleWorkspaceDocsSaveAs'
     */
    @Test
    public void googleWorkspaceDocsSaveAsTest() {
        // TODO: test googleWorkspaceDocsSaveAs
    }

}
