/*
 * Carbon
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.carbonai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.carbonai.client.model.OrderDir;
import com.konfigthis.carbonai.client.model.OrganizationUserFilesToSyncFilters;
import com.konfigthis.carbonai.client.model.OrganizationUserFilesToSyncOrderByTypes;
import com.konfigthis.carbonai.client.model.Pagination;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganizationUserFilesToSyncQueryInput
 */
public class OrganizationUserFilesToSyncQueryInputTest {
    private final OrganizationUserFilesToSyncQueryInput model = new OrganizationUserFilesToSyncQueryInput();

    /**
     * Model tests for OrganizationUserFilesToSyncQueryInput
     */
    @Test
    public void testOrganizationUserFilesToSyncQueryInput() {
        // TODO: test OrganizationUserFilesToSyncQueryInput
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

    /**
     * Test the property 'orderBy'
     */
    @Test
    public void orderByTest() {
        // TODO: test orderBy
    }

    /**
     * Test the property 'orderDir'
     */
    @Test
    public void orderDirTest() {
        // TODO: test orderDir
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'includeRawFile'
     */
    @Test
    public void includeRawFileTest() {
        // TODO: test includeRawFile
    }

    /**
     * Test the property 'includeParsedTextFile'
     */
    @Test
    public void includeParsedTextFileTest() {
        // TODO: test includeParsedTextFile
    }

    /**
     * Test the property 'includeAdditionalFiles'
     */
    @Test
    public void includeAdditionalFilesTest() {
        // TODO: test includeAdditionalFiles
    }

}
